project:
  type: website
  output-dir: docs
  execute-dir: project
  render:
    - "*.qmd"
  resources:
    - images/**

website:
  title: "CurbRisk-AV"
  site-url: https://jonathanwilsonami.github.io/curbrisk-av/
  repo-url: https://github.com/jonathanwilsonami/curbrisk-av

  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About"
      - href: paper.qmd
        text: "Project Paper"

format:
  html:
    theme: cyborg
    css: styles.css
    toc: true
    include-in-header:
      - text: |
          <link rel="stylesheet"
                href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

bibliography: references.bib
csl: https://www.zotero.org/styles/ieee